name: probalkozas
favicon: null
layout_spectrum: 0.29664
typography_spectrum: 0.82246
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#006183'
    - '#030505'
    - '#d3d5c7'
    - '#a0979a'
    - '#a23a0f'
  brandStrength: 0.05499341688118875
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
