name: probalkozas
favicon: null
layout_spectrum: 0.552111150464043
typography_spectrum: 0.6550223610829562
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.05499341688118875
  lightness: 0.6981635270640254
  saturation: 0.6710738053079695
  rhythmicContrast: 0.5171763473190367
purpose: []
